name: Deploy to AWS

on:
  push:
    branches:
      - main  # Change this to your target branch
  workflow_dispatch:  # ðŸ‘ˆ Adds manual trigger option
    inputs:
      region:
        description: "AWS Region"
        required: true
        # default: "      "
 
permissions:
  id-token: write # This is required for requesting the JWT


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502
        with:
          role-to-assume: arn:aws:iam::043309359569:role/OIDC_Github_access
          role-session-name: OIDC_Github_access
          aws-region: "us-east-1"

      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1  # Change to your AWS region

      - name: Deploy using AWS CLI
        run: |
          aws s3 ls                      # Example AWS command
          aws s3 sync . s3://sas-github-workflow --delete
      
      - name: verify AWS credentials
        run:  aws sts get-caller-identity

